#!/bin/bash

# These are initiated by nems-quickfix (daily cron)
# However they are NOT system updates, so they ignore the update settings
# By contrast, these are just local cleanup operations not involving updates

echo "Running cleanup tasks..."

  if [[ -f /var/www/nconf/temp/generate.lock ]]; then
    printf "Resetting NEMS NConf generate.lock..."
    rm -f /var/www/nconf/temp/generate.lock
    sleep 1
    echo " done."
  fi

