#!/usr/bin/env php
<?php
  $cutoff = intval(shell_exec('/usr/local/bin/nems-info perfdata_cutoff'));
  if ($cutoff > 0) {
    $file = '/usr/local/nagios/var/perfdata.log';
    $datachanged = 0;

    $perfdata = new SplFileObject($file);
    $counter = 0;
    while (!$perfdata->eof()) {
      $line = $perfdata->fgets();
      $tmp = explode('||',$line);
      $timestamp = $tmp[0];
      if ($timestamp < strtotime($cutoff . ' days ago')) {
        if (strlen($timestamp) > 0 && $timestamp > 0) {
          // Found some timestamps that are older than $cutoff.
          // Delete those lines from $file using sed.
          $result = shell_exec("sed -i '/^$timestamp||/d' $file");
          $counter++;
        }
      }

    }
    $perfdata = null;

    if ($counter > 0) {
      echo 'Purged all perfdata that is older than ' . $cutoff . ' days.';
    } else {
      echo 'There was no perfdata older than ' . $cutoff . ' days. Nothing purged.';
    }

  } else {
    echo 'perfdata will not be purged since no cutoff is specified in NEMS SST.';
  }
  echo PHP_EOL;
?>
